[package]
name = "create-post"
version = "0.1.0"
authors = ["Jon Grythe St√∏dle <jon@stodle.net>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
structopt = "0.3"
chrono = "0.4"
